version: '2'
services:

  videofaces-mysql:
    build: videofaces-mysql/.
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videofaces

  backend-rest:
    image: dsevilla/videofaces-backend-rest:1.0
    ports:
      - 8080:8080
    environment:
      - SQL_SERVER=videofaces-mysql
